<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class surat_keterangan_kematian extends Model
{
    use HasFactory;

    protected $fillable = [
        'nama_kepala_keluarga',
        'nomor_kepala_keluarga',
        'NIK',
        'nama_jenazah',
        'jenis_kelamin',
        'tanggal_lahir_jenazah',
        'umur_jenazah',
        'tempat_kelahiran',
        'agama',
        'pekerjaan',
        'alamat_jenazah',
        'desa_kelurahan_jenazah',
        'kecamatan_jenazah',
        'kabupaten_kota_jenazah',
        'provinsi_jenazah',
        'anak_ke',
        'tanggal_kematian_jenazah',
        'pukul',
        'sebab_kematian',
        'tempat_kematian',
        'yang_menerangkan',
        'nik_ayah',
        'nama_ayah',
        'tanggal_lahir_ayah',
        'umur_ayah',
        'pekerjaan_ayah',
        'alamat_ayah',
        'nik_ibu',
        'nama_ibu',
        'tanggal_lahir_ibu',
        'umur_ibu',
        'pekerjaan_ibu',
        'alamat_ibu',
        'nik_pelapor',
        'nama_pelapor',
        'umur_pelapor',
        'jenis_kelamin_pelapor',
        'pekerjaan_pelapor',
        'alamat_pelapor',
        'nik_saksi1',
        'nama_saksi1',
        'umur_saksi1',
        'pekerjaan_saksi1',
        'alamat_saksi1',
        'nik_saksi2',
        'nama_saksi2',
        'umur_saksi2',
        'pekerjaan_saksi2',
        'alamat_saksi2',
        'desa_kelurahan_ibu',
        'kabupaten_kota_ibu',
        'kecamatan_ibu',
        'provinsi_ibu',
        'desa_kelurahan_ayah',
        'kabupaten_kota_ayah',
        'kecamatan_ayah',
        'provinsi_ayah',
        'desa_kelurahan_pelapor',
        'kabupaten_kota_pelapor',
        'kecamatan_pelapor',
        'provinsi_pelapor',
        'desa_kelurahan_saksi1',
        'kabupaten_kota_saksi1',
        'kecamatan_saksi1',
        'provinsi_saksi1',
        'desa_kelurahan_saksi2',
        'kabupaten_kota_saksi2',
        'kecamatan_saksi2',
        'provinsi_saksi2',
        'kode_wilayah',
        'jabatan',
        'nomor_surat',
    ];
}
